### ISSUE TITLE
the bot does not start

### ISSUE THREAD

**Issue by trakds** [conor19w/Binance-Futures-Trading-Bot#59]
PS C:\Users\komp\Desktop\Binance-Futures-Trading-Bot-main> python --version
Python 3.7.0
PS C:\Users\komp\Desktop\Binance-Futures-Trading-Bot-main> python LiveTrading.py
Traceback (most recent call last):
  File "LiveTrading.py", line 7, in <module>
    import SharedHelper
  File "C:\Users\komp\Desktop\Binance-Futures-Trading-Bot-main\SharedHelper.py", line 3, in <module>
    import BotClass
  File "C:\Users\komp\Desktop\Binance-Futures-Trading-Bot-main\BotClass.py", line 55
    match self.strategy:
             ^
SyntaxError: invalid syntax

**Comment by trakds** [comment]
the previous version of the bot worked

**Comment by conor19w** [comment]
You need to be running with python 3.11
