### ISSUE TITLE
Bot cannot run ubuntu os. Pls help!!!

### ISSUE THREAD

**Issue by braverynew** [conor19w/Binance-Futures-Trading-Bot#61]
I had error when running bot on ubuntu 22.04, python 3.11
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.11/site-packages/binance/threaded_stream.py", line 59, in run
    self._loop.run_until_complete(self.socket_listener())
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 629, in run_until_complete
    self._check_running()
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 588, in _check_running
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running
/usr/local/lib/python3.11/threading.py:1047: RuntimeWarning: coroutine 'ThreadedApiManager.socket_listener' was never awaited
  self._invoke_excepthook(self)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
How to fix it???

**Comment by alkhachatryan** [comment]
Same here.
@conor19w hello

**Comment by alkhachatryan** [comment]
https://github.com/sammchardy/python-binance/pull/1404

I fixed it here

**Comment by casper123s** [comment]
to fix your trouble check this [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
